### ISSUE TITLE
will scroll support self-destruct op code in future?

### ISSUE THREAD

**Issue by byte-ramble** [scroll-tech/zkevm-circuits#1076]
### Describe the feature you would like

if plan to support, what time it will upgrade, and does the old smart-contract also work with self-destruct op code?

**Comment by Vtalike** [comment]
> ### Describe the feature you would like
> 
> if plan to support, what time it will upgrade, and does the old smart-contract also work with self-destruct op code?
> 
> ### Additional context
> 
> _No response_

**Comment by Viktor110** [comment]
> ### Describe the feature you would like
> 
> if plan to support, what time it will upgrade, and does the old smart-contract also work with self-destruct op code?
> 
> ### Additional context
> 
> _No response_

**Comment by lispc** [comment]
No
