### ISSUE TITLE
32-bit support

### ISSUE THREAD

**Issue by timmyjose** [scroll-tech/zkevm-circuits#1077]
### Describe the feature you would like

My team and I have been looking at 32-bit support for `zkevm-circuits`.  Currently, builds fails due to this check - https://github.com/scroll-tech/zkevm-circuits/blob/develop/zkevm-circuits/src/lib.rs#L24, which forbids non-64 bit builds.

Of course, removing this check does not succeed since I presume there are a lot more code changes that would need to be done to make it work on 32-bit platforms.

For our specific usecase, `K=12`, and we are not really concerned about performance right now. Is there a way to make it work for 32-bit platforms? If so, potentially what changes would need to be done?

Thanks!

### Additional context

Attempting to build for 32-bit platforms.

**Comment by timmyjose** [comment]
Any ideas/thoughts on this? If there is no plan to support 32-bit (for technical/logistical) reasons, it'd be great to see some confirmation of that so that we can close this issue. Thanks!

**Comment by lispc** [comment]
yes nowadays modern CPU is almost all x86-64 and aarch64.  Unless we want to support wasm32 or riscv (we have no such plan in forseeable future), assuming 64bit makes sense for us.

**Comment by timmyjose** [comment]
> yes nowadays modern CPU is almost all x86-64 and aarch64. Unless we want to support wasm32 or riscv (we have no such plan in forseeable future), assuming 64bit makes sense for us.

Okay, thank you for the update!
