### ISSUE TITLE
Unable to switch to Scroll

### ISSUE THREAD

**Issue by FabioT81** [scroll-tech/zkevm-circuits#1131]
### Describe the bug

For a few days I have been experiencing problems with the Rabby wallet. If I'm on Syncswap (Era network) and I want to switch to Scroll I can't. It already happened to me some time ago on the Ambient dex. What could it be? I tried uninstalling Rabby but it didn't solve the problem.

**Comment by lispc** [comment]
no a circuit issue.  You can go to discord for this
