### ISSUE TITLE
Constraint failure while replaying some mainnet TX with access list

### ISSUE THREAD

**Issue by noel2004** [scroll-tech/zkevm-circuits#1138]
Some tx on mainnet like
[0xceeac2b8e36e6de05bb0a625781f044e4be833b917c984584c3839755e78ce83]
(https://etherscan.io/tx/0xceeac2b8e36e6de05bb0a625781f044e4be833b917c984584c3839755e78ce83)
or
[0x94604c865c331ae66a80eb199264b3f317e4aab125a3463aea527c6f77e12898](https://etherscan.io/tx/0x94604c865c331ae66a80eb199264b3f317e4aab125a3463aea527c6f77e12898)

would encounter constraint error and lookup failure while being replayed by our tools. The error looks lile:

> [2024-03-12T12:53:18Z ERROR mainnet] ERR: Constraint 4 ('section_rlc accumulation: r = rand^20, section_rlc' = section_rlc * r + field_rlc'') in gate 1212 ('tx access list') is not satisfied in Region 310 ('tx table aux') at offset 669
>     - Column('Advice', 3 - )@0 = 1
>     - Column('Advice', 349 - )@0 = 0
>     - Column('Advice', 370 - )@0 = 1
>     - Column('Advice', 371 - )@0 = 1
>     - Column('Advice', 373 - )@1 = 0x21561e53104b2a06ab619c4b89402a3f6bad6f6d993a155c982422de19ec08b0
>     - Column('Advice', 375 - )@0 = 1
>     - Column('Advice { phase: Phase(1) }', 351 - )@0 = 0xb6dd20903504285b86a714980fe1b17c0e4eaa4f1a842619fbea211f5079d0a
>     - Column('Advice { phase: Phase(1) }', 351 - )@1 = 0x17ee1648645d019d4d554685dd551353fcde3b1b7da642b4bed33dd93d5b8218
>     - Column('Fixed', 0 - )@0 = 1
> 
> [2024-03-12T12:53:18Z ERROR mainnet] ERR: Lookup Sig table lookup(index: 92) is not satisfied in Region 310 ('tx table aux') at offset 12

It can be reproduced by following command (suppose we have a geth node with debug API availiable in localhost:8545

```
RUST_LOG=debug TX_ID=0x94604c865c331ae66a80eb199264b3f317e4aab125a3463aea527c6f77e12898 GETH0_URL=http://localhost:8545 cargo test --features=scroll --release test_mock_prove_tx
```

**Comment by noel2004** [comment]
Guess the constraint issue if caused by empty `storageKey` slot in access list.

[Tx with access list without empty slot of `storageKey`](https://etherscan.io/tx/0x7e9b4541363dab7907f1304edf357f341f446298e2da723ea7397638fd0111b4?__cf_chl_tk=Ls_yKJ9RQnhKQB1iBcpx7sDpimaCIrCBbLfCOVoPuK4-1710293695-0.0.1.1-1450#accesslist) would not raise this issue

**Comment by DreamWuGit** [comment]
it is signature lookup fail in tx circuit,  waitting Pr ray's tx circuit audit fix merge then re-test.

**Comment by noel2004** [comment]
While testing [0x94604c865c331ae66a80eb199264b3f317e4aab125a3463aea527c6f77e12898](https://etherscan.io/tx/0x94604c865c331ae66a80eb199264b3f317e4aab125a3463aea527c6f77e12898), the constraint error found before has been fixed, but we have another lookup err now:

> 
> [2024-04-24T08:10:48Z ERROR mainnet] ERR: Lookup Decoding table stack op POP correspondence(index: 18) is not satisfied in Region 228981 ('RLP sm region') at offset 12083
> [2024-04-24T08:10:48Z ERROR mainnet] ERR: Lookup Decoding table stack op POP correspondence(index: 18) is not satisfied in Region 228981 ('RLP sm region') at offset 12054

**Comment by DreamWuGit** [comment]
after run testing against latest develop branch,  guess not signature data error.
  ```
        "v": 1,
          "r": "0xb747fec9bd97c46da0af4750d0c97423392fd045512b566d72519e102173d6d6",
          "s": "0x1390614df6318f45bcc1d189d846135d843982e5de35913a289376b20066b07e",
```
seems access list  RLP encoding issue, will dig more.

**Comment by DreamWuGit** [comment]
it is caused by access list data, if tx has no access list , can pass after signature fix in tx circuit .
