### ISSUE TITLE
For EIP1559 tx, v in signature is not correctly lookup

### ISSUE THREAD

**Issue by noel2004** [scroll-tech/zkevm-circuits#1141]
In tx circuit we would lookup signature from sig table. While the v of carried in signature being lookup it need to be converted into the v of a ecc signature (0 or 1). The conversion depend on the type of tx.

In [the current code](https://github.com/scroll-tech/zkevm-circuits/blob/888824a42df2a8983a6e0336030440938c2ea022/zkevm-circuits/src/tx_circuit.rs#L2261), the v seems would only be converted for EIP155/pre155 type (tx type is `0` or `1`). For EIP1559 tx (tx type is `2`), the v would be always 0. So we would hit following lookup error in ~50% chance:

```
[2024-03-12T05:40:59Z ERROR mainnet] ERR: Lookup Sig table lookup(index: 92) is not satisfied in Region 298 ('tx table aux') at offset 12
```

Update the code with following expression would elimiate the lookup error in [this mainnet tx](https://etherscan.io/tx/0x7e9b4541363dab7907f1304edf357f341f446298e2da723ea7397638fd0111b4). But we notice that there is still [some other constraints on sig_v](https://github.com/scroll-tech/zkevm-circuits/blob/888824a42df2a8983a6e0336030440938c2ea022/zkevm-circuits/src/tx_circuit.rs#L1619) is not actived in EIP1559 tx, lead to a under constraintion.

``` rust
             let v = is_eip155(meta) * (sig_v.expr() - 2.expr() * chain_id - 35.expr())
                + is_pre_eip155(meta) * (sig_v.expr() - 27.expr())
                + meta.query_advice(is_eip1559, Rotation::cur()) * sig_v.expr();
```

**Comment by DreamWuGit** [comment]
it is signature lookup fail in tx circuit,  waitting Pr ray's tx circuit audit fix merge then re-test.

**Comment by noel2004** [comment]
Still not fixed since here:
https://github.com/scroll-tech/zkevm-circuits/blob/ceba59e7383d58a3a40f1f5ffd267300865b41ec/zkevm-circuits/src/tx_circuit.rs#L2654

The condition for `EIP1559` should be added

**Comment by DreamWuGit** [comment]
> Still not fixed since here:
> 
> https://github.com/scroll-tech/zkevm-circuits/blob/ceba59e7383d58a3a40f1f5ffd267300865b41ec/zkevm-circuits/src/tx_circuit.rs#L2654
> 
> The condition for `EIP1559` should be added

changing as below doesn't work, need figure out V value setting here.
 ```
let is_eip155_or_post = is_eip155(meta) + meta.query_advice(is_eip1559, Rotation::cur())
                 + meta.query_advice(is_eip2930, Rotation::cur());
 let v = is_eip155_or_post * (sig_v.expr() - 2.expr() * chain_id - 35.expr())
               + is_pre_eip155(meta) * (sig_v.expr() - 27.expr());
```

**Comment by DreamWuGit** [comment]
close as fixed.
