### ISSUE TITLE
add smart contract call tests in the integration test

### ISSUE THREAD

**Issue by icemelon** [scroll-tech/zkevm-circuits#118]
The goal of this test is to generate a block that includes the execution of Greeter smart contract `set_value` and `retrieve` call, and then run through the zkevm circuits and be able to generate the proof and verify it.

Reference: https://github.com/appliedzkp/zkevm-circuits/blob/main/integration-tests/tests/circuits.rs#L104

**Comment by lispc** [comment]
almost done. except two big issues

1.  bus-mapping for calldataload
2. sstore needs prev_value / commited_value from trace
