### ISSUE TITLE
Improving L2 gas fee predictability - EIP-1559

### ISSUE THREAD

**Issue by Kajko25** [scroll-tech/zkevm-circuits#1249]
### Describe the feature you would like

Good morning ladies and gentlemen!

We are all well aware that the whole team is working hard on new features and improvements to improve the Scroll zkEVM network. We are very grateful to you for this - especially for the recent addition of EIP-4844 which has greatly reduced the price of transactions. 

But are you planning to use data compression in the near future to further reduce gas costs and add support for the EIP-1559 fee mechanism in Ethereum.

I think this would be a step in the right direction. 

Greetings 
Kajko24

**Comment by lispc** [comment]
are you planning to use data compression in the near future to further reduce gas costs and add support for the EIP-1559 fee mechanism in Ethereum?:

yes, DA compression and 1559 will be on mainnet late June. Next upgrade.
