### ISSUE TITLE
split one l1 block into multi circuit instance

### ISSUE THREAD

**Issue by lispc** [scroll-tech/zkevm-circuits#149]
it's very likely that a circuit cannot contain a full l1 block. So we may need to do this splitting.

**Comment by otrsk** [comment]
@lispc when are we supposed to use the zkEVM 'project' ( https://github.com/orgs/scroll-tech/projects/2/views/1  )?

**Comment by lispc** [comment]
> @lispc when are we supposed to use the zkEVM 'project' ( https://github.com/orgs/scroll-tech/projects/2/views/1 )?

We used it before. Currently we mainly rely on jira.

**Comment by otrsk** [comment]
> > @lispc when are we supposed to use the zkEVM 'project' ( https://github.com/orgs/scroll-tech/projects/2/views/1 )?
> 
> We used it before. Currently we mainly rely on jira.

Gotcha, thx

**Comment by lispc** [comment]
currently it takes 7000 rows for proving 1540 opcodes with 5 txs(4 succ + 1 fail) in multi-erc20.json.

So 2**18 circuit can prove 187 erc20 transfers.

**Comment by lispc** [comment]
this design now is called "continuation" widely.  A long term big task. Will revisit later.
