### ISSUE TITLE
New design of public input circuit

### ISSUE THREAD

**Issue by kunxian-xia** [scroll-tech/zkevm-circuits#217]
The design doc is [here](https://hackmd.io/KvmRRWRtT6yvwSXGfysLxQ).  

The overall goal is to reduce the gas cost spent in verifying the final proof. The main observation is that `keccak()` function is much cheaper than `AddMod/MulMod`.

The new design is using keccak to compress the raw public inputs. The tx data is first hashed using keccak to get `tx_hash`.   Then we will hash these 32-bytes `tx_hash` using keccak.

 ```
   keccak([
        coinbase,
        gas_limit,
        number,
        time,
        difficulty,
        base_fee,
        chain_id,
        prev_block_hashes[0],
        ...,
        prev_block_hashes[255],
        
        block_hash,
        prev_state_root,
        state_root,
        
        keccak(rlp(txs[0])), 
        keccak(rlp(txs[1])), 
        keccak(rlp(txs[2])), 
        keccak(rlp(txs[3])), 
        ....,
        keccak(rlp(txs[n-1])), 
        DUMMY_PADDING_TX_HASH,
        ....,
        DUMMY_PADDING_TX_HASH,        
    ])
```
The impl of this new PI circuit can be found at the [feat/pi-circuit](https://github.com/scroll-tech/zkevm-circuits/tree/feat/pi-circuit) branch.

**Comment by OrestTa** [comment]
@kunxian-xia you might wanna create an asana card for internal prioritisation

**Comment by kunxian-xia** [comment]
The discussion there https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/915#issuecomment-1326643915 helps to understand how to generate randomness in a sound way.
