### ISSUE TITLE
Unable to run make test-all on MacOS Ventura 13.0

### ISSUE THREAD

**Issue by elielnfinic** [scroll-tech/zkevm-circuits#219]
Hi everybody,

I am unable to run `make test` or `make test-all` on MacOS Ventura 13.0
Here is the error I am getting 
```
error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the 'nightly-2022-08-23-aarch64-apple-darwin' toolchain
make: *** [test] Error 1

```

Is there any particular toolchain that I need to run this or any configuration I need to set up on my computer ?

Best regards.

**Comment by NTP-996** [comment]
The new chip of mac creates some problems I think. Maybe you can try to run virtual Ubuntu

**Comment by OrestTa** [comment]
@NazariiDenha , maybe you might know?
