### ISSUE TITLE
2 same swap errors 

### ISSUE THREAD

**Issue by nazarov1ch** [scroll-tech/zkevm-circuits#258]
Everything worked good except 2 same errors
Transaction Hash 0x9a93fcb277d1c87d396d88a973ab32755955bf55466e187b3eb1d5a0b6d8669d
Transaction Hash 0x398b7ef3fe60774aff6d89b8a507178984b997f6b04e1f668d0a1e2b4bbee402
![2023-01-17 (1)](https://user-images.githubusercontent.com/116263637/212899900-8bc23328-0165-420d-8c84-b44dcaf3fd95.png)
![2023-01-17](https://user-images.githubusercontent.com/116263637/212899923-8f723456-06fd-4abb-b43f-43fcaa0d70e8.png)

**Comment by OrestTa** [comment]
@nazarov1ch thanks for reporting; are you still seeing this behaviour? Are you able to reproduce it? We used to have some health issues last week, cf. https://status.scroll.io

**Comment by nazarov1ch** [comment]
It was only 2 times in arrow, I havent caught this error again. Thanks for reply.

**Comment by OrestTa** [comment]
OK, probably due to said health issues then, thanks for confirming.
