### ISSUE TITLE
The "zero" account should has 0 value for codehash

### ISSUE THREAD

**Issue by noel2004** [scroll-tech/zkevm-circuits#286]
Currently busmapping purpose an "zero" `AccountData` has codehash value with `Keccak(nil)`:

https://github.com/scroll-tech/zkevm-circuits/blob/27fa89f8776e0a7f79ab38988bf2fded57a8a719/bus-mapping/src/state_db.rs#L106-L112

This may cause some issues like on creating a new contract on empty address (on which the trie still have no a leaf), we get a mpt update entry for codehash `Keccak(nil)` -> `<contract codehash>` instead of `0` -> `<contract codehash>`

Also while reading a non-exist address, the account object being put into `stateDb` is not match to the codehash value it is read from trace (read zero but we have `Keccak(nil)` in `stateDb`

I purpose to update the 'zero' account object with codehash equal to zero, also an additional updating of codehash to `Keccak(nil)` when touching an address, which is purposed in [EIP-2929](https://eips.ethereum.org/EIPS/eip-2929)

**Comment by lispc** [comment]
"is not match to the codehash value it is read from trace":    the struct log or smt trace? or can you paste the related codes?

**Comment by noel2004** [comment]
It should be from struct log: when an `EXTCODEHASH` on an nonexisted address is encountered the log would indicate a zero codehash. rw table would take it as 'current value' while the 'old value' is still `keccak(nil)`

That is why we have to [skip a sanity check for the consistence of old value from rw table and the current state value before new state](https://github.com/scroll-tech/zkevm-circuits/blob/1308f42190fa95d6c23b78991175f7783818e6fe/zktrie/src/state/witness.rs#L243) for the codehash case.

**Comment by lispc** [comment]
related to https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1101

**Comment by noel2004** [comment]
ok. So it should be:

1. in mpt circuit, the empty account **MUST** has an codehash of `keccak(nil)`
2. in rw table, only the nonexist case would read codehash as 0, and this would not be propagated to the mpt circuit for nonexist proof type is triggerred.

**Comment by noel2004** [comment]
Turn this issue into mpt circuit: https://github.com/scroll-tech/mpt-circuit/issues/17
