### ISSUE TITLE
precompile codehash could be unsound

### ISSUE THREAD

**Issue by lightsing** [scroll-tech/zkevm-circuits#315]
In new test cases for begin-tx with precompile #306, we found that call to precompile with value will cause CodeDB initialise the code hash of precompile to EMPTY_HASH (prev value: Word::zero() since non-exist).

This could be unsound since the code hash of precompile address would be inconsistent (Word::zero() for non-exist account, EMPTY_HASH for empty account).

**Comment by lispc** [comment]
fixed
