### ISSUE TITLE
bug: returndatasize after successful create

### ISSUE THREAD

**Issue by lispc** [scroll-tech/zkevm-circuits#322]
### Describe the bug

in EIP, it is said "CREATE and CREATE2 are considered to return the empty buffer in the success case and the failure data in the failure case.". I think it is inconsistent with current code:

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/65577a99d042c326cfb9ba5131d804805d504b0f/bus-mapping/src/circuit_input_builder/input_state_ref.rs#L859

**Comment by z2trillion** [comment]
EIP 211: https://eips.ethereum.org/EIPS/eip-211

**Comment by lispc** [comment]
fixed
