### ISSUE TITLE
err handling for return/revert stack/oog

### ISSUE THREAD

**Issue by lispc** [scroll-tech/zkevm-circuits#337]
### Describe the feature you would like

background: https://github.com/scroll-tech/zkevm-circuits/pull/304#pullrequestreview-1300690631

i am afraid the codes are not robust enough...

https://github.com/scroll-tech/zkevm-circuits/blob/2a876525fd9bc39f2a1bf1a60fc1f8d6c6b90512/bus-mapping/src/circuit_input_builder/input_state_ref.rs#L1055-L1057

i need some test cases:

1. return on empty stack
2. return but gas not enough, due to memory expansion (non creation case)
3. revert on empty stack
4.  revert but gas not enough, due to memory expansion

not high priority

**Comment by DreamWuGit** [comment]
`DynamicMemoryExpansion` error will cover some of them. 
```
    /// Out of Gas for CREATE, RETURN, REVERT, which have dynamic memory
    /// expansion gas cost
    DynamicMemoryExpansion,
```
