### ISSUE TITLE
bug: callcode inside staticcall is allowed..

### ISSUE THREAD

**Issue by lispc** [scroll-tech/zkevm-circuits#356]
### Describe the bug

yes i rechecked with geth and doc..

"CALL with value must not be in static call stack" no correct.

**Comment by lispc** [comment]
static_CheckOpcodes2_d3_g0_v0

**Comment by silathdiir** [comment]
Fixed in https://github.com/scroll-tech/zkevm-circuits/pull/360 by @lispc
