### ISSUE TITLE
bug: oog sstore is of more "priority" than error write permission

### ISSUE THREAD

**Issue by lispc** [scroll-tech/zkevm-circuits#357]
### Describe the bug

static_callcodecall_10_OOGE_d0_g0_v0

first, check gas
then, check is_static

so oog sstore can happend inside is_static..

**Comment by silathdiir** [comment]
Fixed in https://github.com/scroll-tech/zkevm-circuits/pull/360 by @lispc

**Comment by lispc** [comment]
i think there is some unsoundness here.  Imagine we have a trace, a step is write inside a static call , in the same time, gas is not enough.   According to evm standard, this case should be handled by OOG instead of WritePermission (evm first checks gas, then check is_static write). But if we use the 'ErrorWriteProtectionGadget' to process this ExecutionState, everything will be ok... Both OOG and ErrorWriteProtectionGadget can be used to process this ExecutionState, it is not good...

**Comment by lispc** [comment]
low priority.

**Comment by lispc** [comment]
currently this is is fixed by constrain "when this err happens, some other condition(may trigger other errs) must be XXX" in err gadgets.  It is sound,  but later we may better refactor codes in a more consistent & easier to understand way
