### ISSUE TITLE
pools

### ISSUE THREAD

**Issue by Bombonchik** [scroll-tech/zkevm-circuits#374]
### Describe the bug

When attempting to add a liquidity pool on Uniswap testing the Scroll Alpha Testnet, the token selection process only allows for the selection of a single token, which prevents the creation of a functional pool.
Wallet: 0x268dC0F694ba3219d0c541D5F7a17B93ad24eC72

**Comment by rrzhang139** [comment]
This is not related to the zkevm-circuits repo, closing this. Please ask this in our discord!
