### ISSUE TITLE
Pool creation limitation on Uniswap

### ISSUE THREAD

**Issue by dreariesfki** [scroll-tech/zkevm-circuits#378]
### Describe the bug

A token selection issue on Uniswap testing the Scroll Alpha Testnet prevents the creation of liquidity pools, which negatively impacts user engagement and adoption rates.
Wallet: 0x235014a26D821a86794bbEd6AAa577126cbe57c6

**Comment by rrzhang139** [comment]
This is not related to the zkevm-circuits repo, closing this. Please ask this in our discord!
