### ISSUE TITLE
Scroll Bridge

### ISSUE THREAD

**Issue by duxin0817060114** [scroll-tech/zkevm-circuits#379]
### Describe the bug

Transaction Details
 Transaction Hash
0x1bffa6bdea1e65d3c1115d52fb225497ca105bae9343256f77a8a496c5c7d342
 Result
 Success
 Status
Confirmed Confirmed by 140 blocks
 Block
[226167](https://blockscout.scroll.io/block/226167)
 Timestamp
 7 minutes ago | March-08-2023 10:24:31 AM +8 UTC | Confirmed within <= 3.0 seconds
 From
[0x6453b156638066A483156901A5D4C50C9BE18E95](https://blockscout.scroll.io/address/0x6453b156638066A483156901A5D4C50C9BE18E95)
 Interacted With (To)
[TransparentUpgradeableProxy (0x6d79aa–fb0649)](https://blockscout.scroll.io/address/0x6d79Aa2e4Fbf80CF8543Ad97e294861853fb0649)
 Value
0.85319511434288 ETH
 Transaction Fee
0.00000474756 ETH

**The Scroll Bridge problem,Transaction Confirmed，Goerli Testnet did not receive ETH**

**Comment by rrzhang139** [comment]
This is not related to the zkevm-circuits repo, closing this. Please ask this in our discord!
