### ISSUE TITLE
CREATE2_GAS_PER_CODE_WORD etc is not defined when "shanghai" feature is not enabled

### ISSUE THREAD

**Issue by noel2004** [scroll-tech/zkevm-circuits#509]
Some constants like `CREATE2_GAS_PER_CODE_WORD`, `CREATE_GAS_PER_CODE_WORD`, `MAX_INIT_CODE_SIZE` is used in [`evm_circuit` like `create.rs`](https://github.com/scroll-tech/zkevm-circuits/blob/9f366000091f7fb5aeba4fb3b5b2a17de4c7c0dc/zkevm-circuits/src/evm_circuit/execution/create.rs#L30), however, this constants is not defined [if 'shanghai' feature is not enabled](https://github.com/scroll-tech/zkevm-circuits/blob/9f366000091f7fb5aeba4fb3b5b2a17de4c7c0dc/eth-types/src/evm_types.rs#L95)

**Comment by silathdiir** [comment]
Seems [this code of mod gas_create](https://github.com/scroll-tech/zkevm-circuits/blob/9f366000091f7fb5aeba4fb3b5b2a17de4c7c0dc/eth-types/src/evm_types.rs#LL75C5-L75C15) is used for shanghai, and [code of mod gas_create](https://github.com/scroll-tech/zkevm-circuits/blob/9f366000091f7fb5aeba4fb3b5b2a17de4c7c0dc/eth-types/src/evm_types.rs#L96) for not-shanghai.

Do you mean this is not right method for constant definition of shanghai feature? Thanks.

**Comment by noel2004** [comment]
My fault. Never mind ...
