### ISSUE TITLE
Calculate l1fee cost from pre-EIP155 fashion rlc of tx

### ISSUE THREAD

**Issue by noel2004** [scroll-tech/zkevm-circuits#515]
Currently, the l1fee is calculated [at the beginning of a tx being committed](https://github.com/scroll-tech/go-ethereum/blob/ad43d0ea3fca425636d7478d8f6e1a215385058d/core/state_transition.go#L186). The rlp encoded of tx is used to calculated the cost of l1fee, with the fashion of calldata cost (4 for zero byte and 16 for non-zero). At this step, the chainID is still not avaliable so **the tx is rlp encoded with the pre-EIP155 way** (i.e. 6 rather than 9 items being involved). The chainID and signature part is added as a constant cost later

To prove l1fee cost, in tx circuit we may need:

1. A new field to store the pre-EIP155 rlp encoding of tx (may bring in many cost?)
2. Prove the l1fee cost just like call data cost.

**Comment by kunxian-xia** [comment]
The problem is that the bytes returned by `raw, err := rlpEncode(tx)` does not necessarily  equal to `tx.rlp_unsigned()`. 
Note that
- `rlpEncode(tx) = rlp([nonce, gas_price, gas, to, value, data, 0, 0, 0])[:-3]` and 
- `tx.rlp_unsigned() = rlp([nonce, gas_price, gas, to, value, data]`. 

There is a subtlety here: 
> it could happen that `rlpEncode(tx)` starts with bytes like `[0xf9, 0x01, 0x02]` while the `tx.rlp_unsigned()` starts with `[0xf8, fe]`.

**Comment by kunxian-xia** [comment]
@icemelon @Thegaram I suggest that we should change the impl of `rlpEncode(tx)` to use the rlp signed bytes
```
rlp([nonce, gas_price, gas, to, value, data, v, r, s])
```
Doing that should make the impl of constraining the l1 data fee more easier inside the RLP circuit.

**Comment by kunxian-xia** [comment]
@noel2004 After having discussion with @icemelon and @HAOYUatHZ, we decide to stick with the change proposed above.

**Comment by noel2004** [comment]
That's ok. Should we still need some workaround on calculating the l1fee cost to kept it being consistent with current l2geth?

**Comment by lispc** [comment]
i think this is already finished and can be closed? @noel2004

**Comment by noel2004** [comment]
> i think this is already finished and can be closed? @noel2004

Yes. Has been fixed
