### ISSUE TITLE
Page transfer bug on Unifra Explorer

### ISSUE THREAD

**Issue by htanhzrother** [scroll-tech/zkevm-circuits#521]
### Describe the bug

When accessing transaction statistics by wallet address, in the transition between pages, there are 3 errors as follows:
1- Although the number of transactions is not available, the page is still passable.
2- Odd-numbered pages like: 1-3-5-7-... repeat data.
3- Even-numbered pages like: 2-4-6-8-... are empty data.
![trang chẵn](https://github.com/scroll-tech/zkevm-circuits/assets/116946278/fd886ff6-396f-4188-a339-8b92076d3f65)
![trang lẻ 2](https://github.com/scroll-tech/zkevm-circuits/assets/116946278/29920e49-da1d-4f39-a633-92b6756cb94c)
![trang le](https://github.com/scroll-tech/zkevm-circuits/assets/116946278/807a909b-fa65-4f40-8477-bb21251d84a0)

### Concrete steps to reproduce the bug. If it's able reproduce via testool, please share `test_id` from jenkins report

Step1: Go to https://scrollscan.co/
Step2: Fill in the wallet address
Step3: Choose the number of transactions per page (specifically 100/page)
Step4: Continuous page switching

**Comment by dghelm** [comment]
Thanks for taking the time to raise the issue! This repo is dedicated to Scroll's zkEVM circuits, and this report is for a product made by a different team in our community. I'd recommend raising the issue [here](https://github.com/unifra20/scroll-explorer). Closing this issue.
