### ISSUE TITLE
feat: ecrecover precompile

### ISSUE THREAD

**Issue by lispc** [scroll-tech/zkevm-circuits#527]
0. merge the identity precompile PR
1. refactor sig_verify.rs, so instead of using apis like halo2_base::AssignedValue::copy_advice, we create a "r,s,v,hash,is_valid" table (called sig verify table?). Then both tx circuit and evm_circuit::ecrecover can lookup this table?     Another benefit of this is, we no longer leak the complexity of halo2_base to other circuits.    @lispc 
2. evm_circuit side taks. @roynalnaruto

**Comment by kunxian-xia** [comment]
You need also to include the `recovered_addr` in the `SignVerify` table. That is, the table looks like
```
(v, r, s, msg_hash, recovered_addr, is_valid).
```

**Comment by roynalnaruto** [comment]
@lispc we can close this issue right?
