### ISSUE TITLE
Matain scroll's geth docker image

### ISSUE THREAD

**Issue by qy3u** [scroll-tech/zkevm-circuits#531]
### What command(s) is the bug in?

cd integration-tests && ./run.sh --sudo --steps "setup gendata" && cargo test --profile release --test circuits mock_prover::serial_test_evm_circuit_block_transfer_0 --all-features -- --nocapture

### Describe the bug

I am currently running commands under the v0.3.1 tag.(integration-tests can't be build under develop branch: 79caaf4).

Here is the error I encountered:
```
thread 'mock_prover::serial_test_evm_circuit_block_transfer_0' panicked at 'called `Result::unwrap()` on an `Err` value: 
JSONRpcError(JsonRpcClientError(SerdeJson { err: Error("missing field `keccakCodeHash`", line: 1, column: 1060).... }))'
zkevm-circuits/bus-mapping/src/circuit_input_builder.rs:867:18
```

It seems that the issue stems from the fact that the `integration-tests` use the docker image "ethereum/client-go:v1.11.5". When the `eth_getProof` function is called, it returns a different `AccountResult` struct than the one expected by Scroll, as shown in the following code snippets:

ethereum/go-ethereum repository: https://github.com/ethereum/go-ethereum/blob/281e8cd5abaac86ed3f37f98250ff147b3c9fe62/internal/ethapi/api.go#L641-L650

scroll-tech/go-ethereum repository: https://github.com/scroll-tech/go-ethereum/blob/983d6302443376345cbcd66b98382ef94a30f9e7/internal/ethapi/api.go#L638-L649

One possible solution to fix this issue is to maintain a docker image of geth specifically for Scroll.

**Comment by lispc** [comment]
this is a scroll-tech/go-ethereum related issue
