### ISSUE TITLE
memory_opt calcs wrong memory word range

### ISSUE THREAD

**Issue by lightsing** [scroll-tech/zkevm-circuits#540]
current we calc the word by this approach:
```
let start_slot = offset - offset % 32;
let end = offset + length;
let end_slot = end - end % 32;
```
the range is `bytes[start_slot..end_slot+32]`.

consider we are coping memory of first 32 bytes, aka `offset = 0, length = 32`.
the words bytes will be `bytes[0..63]`, there comes an extra word.
expect words bytes to be `bytes[0..31]`, only one word.

This should be fixed, with a low priority.

@DreamWuGit @lispc

**Comment by DreamWuGit** [comment]
it is known edge case like in https://github.com/scroll-tech/zkevm-circuits/blob/memory_opt/bus-mapping/src/evm/opcodes/mload.rs#L62, very low priority for now.

**Comment by naure** [comment]
Can you point to the code to review specifically?

**Comment by naure** [comment]
This should be fixed [here](https://github.com/scroll-tech/zkevm-circuits/pull/541/files#diff-ded09b7b7016017797fa4550d232316de716e483e43ba4f5a192cceb46f36453R340) with the function `align_range`. See also the unittest below. In particular: "When the range ends exactly at a word boundary, it is still ONE WORD."

Please let me know whether we agree on the behavior. (@lightsing @DreamWuGit )

**Comment by lightsing** [comment]
> This should be fixed [here](https://github.com/scroll-tech/zkevm-circuits/pull/541/files#diff-ded09b7b7016017797fa4550d232316de716e483e43ba4f5a192cceb46f36453R340) with the function `align_range`. See also the unittest below. In particular: "When the range ends exactly at a word boundary, it is still ONE WORD."
> 
> Please let me know whether we agree on the behavior. (@lightsing @DreamWuGit )

I aggree with your fix.
