### ISSUE TITLE
Tracking Issue for `bn256` related precompiled contracts

### ISSUE THREAD

**Issue by roynalnaruto** [scroll-tech/zkevm-circuits#563]
### Describe the feature you would like

- [x] #597 
- [x] #594 
- [x] #595 
- [x] #596 
- [x] #651 
- [x] #652
- [x] #682

**Comment by ameya-deshmukh** [comment]
@roynalnaruto hi! Can I work on the invalid input handling issues? Thanks!

**Comment by lispc** [comment]
done
