### ISSUE TITLE
[soundness] is code hash for contract creation in begin_tx constrained anywhere?

### ISSUE THREAD

**Issue by lispc** [scroll-tech/zkevm-circuits#605]
the initcode hash is the poseidon(keccak?) hash of initcode when tx.to = None.

need some connection with tx circuit?

**Comment by lispc** [comment]
a related issue: did we constraint state transition for case A in return_revert here?  https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/6bcb1d052a75886f4a2379347b84fa2bd1ff2bea/zkevm-circuits/src/evm_circuit/execution/return_revert.rs#L97

**Comment by z2trillion** [comment]
The cases aren't mutually exclusive. Case B is `is_root`  and Case C is `not::expr(is_root.expr())`. In B we `require_step_state_transition` directly and in C we construct a restore context gadget which does it here: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/util/common_gadget.rs#L197C12-L197C41.
