### ISSUE TITLE
test: enable state circuit test for every opcode

### ISSUE THREAD

**Issue by lispc** [scroll-tech/zkevm-circuits#63]
Whenever we add an opcode, we add evm circuit test for it using `run_test_circuit_incomplete_fixed_table(witness::build_block_from_trace_code_at_start(&bytecode))`.    

On the other hand, there are only a few hand-written state circuit tests in state.rs. We need to enable state tests for each opcode.

**Comment by lispc** [comment]
lots of tests fail.   state circuit code is old and a bit under tested and under maintained ..

**Comment by lispc** [comment]
done. will submit PR tomorrow

**Comment by HAOYUatHZ** [comment]
closed via https://github.com/appliedzkp/zkevm-circuits/pull/282?
