### ISSUE TITLE
Handling invalid inputs `EcAdd`

### ISSUE THREAD

**Issue by roynalnaruto** [scroll-tech/zkevm-circuits#651]
### Describe the feature you would like

The precompiled contract call `EcAdd` has the following failure cases:
- `P` not on curve
- `Q` not on curve
- Insufficient gas provided (should this be handled elsewhere?)

These cases need to be handled within the `EcAdd` execution state gadget for soundness check on "input bytes"

**Comment by lispc** [comment]
done
