### ISSUE TITLE
test: use scroll block trace in super circuit when "scroll" feature enabled

### ISSUE THREAD

**Issue by lispc** [scroll-tech/zkevm-circuits#655]
### Describe the feature you would like

currently we are some adhoc tricks to pass super circuit tests.  We should upgrade the local scroll l2geth tracer, and process StorageProof like scroll-prover repo.

Some benefits of this change:
(1) for community contributor, it will be easier for them to understand the whole process, they only need to read just one repo. **Currently they have to touch codes in several repos(trace-dumper / traces / scroll-prover / zkevm-circuits) even for simple things like proving their own contracts.**    Further we can write some docs on the topic "how to proving your own sol contracts", and give some examples.
(2) help with tests like https://github.com/scroll-tech/zkevm-circuits/issues/654

**Comment by lispc** [comment]
need to upgrade scroll go mod first

**Comment by lispc** [comment]
Merge ZktrieState and WitnessGenerator？

**Comment by lispc** [comment]
another example is, we have https://github.com/lispc/layer3-tester, we would like to generate test case and test trace inside this repo using `TestContext` directly. Much simpler

**Comment by noel2004** [comment]
Prefer generate a l2trace via `geth_util` directly

like capacity checker, trace can [be dump directly from a “TraceEnv” object](https://github.com/scroll-tech/go-ethereum/blob/b428fa1339afe1cd6b271cce45041b48bd28805a/miner/worker.go#L878). It can be used to replace some part currently inside `geth_util` for trace dumping. (mostly codes [below here](https://github.com/scroll-tech/zkevm-circuits/blob/d0e7a07e8af25220623564ef1c3ed101ce63220e/geth-utils/gethutil/trace.go#L230))

To create `TraceEnv` object we need to provide some instances and most of they have been ready in the `geth_util` route:

+ `ChainConfig`: we have it ready
+ `ChainContext` interface: it is solely used to created a `BlockContext` instance inside the creating route and we had the later ready
+ `consensus.Engine` interface: only for obtaing coinbase address, which is trivial
+ state, parentBlock and current block instance: all we have made ready

So it would not take very much effort to turn the output geth trace into a standard l2trace object. And works required is inside `geth_util`.

After turning to l2trace, we can purne the "mock fill state root" hacking in mpt

**Comment by lispc** [comment]
ok btw we need to support both the l1 old tracer for default mode and scroll tracer for scroll mode
