### ISSUE TITLE
`From<&bus_mapping::circuit_input_builder::ExecStep> for ExecutionState` error reporting

### ISSUE THREAD

**Issue by HAOYUatHZ** [scroll-tech/zkevm-circuits#66]
https://github.com/appliedzkp/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/witness.rs#L320

convert this to an issue in case we forget about it

**Comment by lispc** [comment]
maybe related to <https://github.com/scroll-tech/zkevm-circuits/issues/64>

**Comment by HAOYUatHZ** [comment]
closed via https://github.com/appliedzkp/zkevm-circuits/pull/333
