### ISSUE TITLE
When pop_call_stack=true, call_stack.len() is always equal 1

### ISSUE THREAD

**Issue by dfixx** [scroll-tech/zkevm-circuits#665]
### Describe the bug

https://github.com/scroll-tech/zkevm-circuits/blob/c2c5ecc8d58ac4568dc8365caa8d018a3c2f3135/bus-mapping/src/circuit_input_builder/access.rs#L273C1-L274C1
When pop_call_stack=true, call_stack.len() is always equal 1, so, when pop_call_stack=true, it will keep throwing exceptions? (I am just starting to understand this code. Please ignore if I am mistaken.)

**Comment by lispc** [comment]
there should be at least one call_stack (to, CodeSource::Address(to)) or (address, CodeSource::Tx).  So it should notpop when there is only one call_stack.
