### ISSUE TITLE
Handling invalid inputs for `EcPairing`

### ISSUE THREAD

**Issue by roynalnaruto** [scroll-tech/zkevm-circuits#682]
### Describe the feature you would like

Error cases:
- input length is not a multiple of 192, i.e. `input_len % 192 != 0`
- input length is greater than 4 * 192, as we only allow 4 pairs in one pairing op
- point not on curve G1 (any of the input G1s)
- point not on curve G2 (any of the input G2s)

**Comment by lispc** [comment]
done
