### ISSUE TITLE
macro issue to track bugs in #670 

### ISSUE THREAD

**Issue by zhenfeizhang** [scroll-tech/zkevm-circuits#698]
### Describe the bug

macro issue to track bugs in #670 
- [x] https://github.com/scroll-tech/zkevm-circuits/pull/677 (hot fix, may be improved via #687)
- [x] https://github.com/scroll-tech/zkevm-circuits/pull/686
- [x] https://github.com/scroll-tech/zkevm-circuits/pull/691
- [x] #699 
- [x] #711
  - follow up of #704  
- [x] #713

**Comment by lispc** [comment]
seems done
