### ISSUE TITLE
RETURN_REVERT: distinguish return or revert opcode

### ISSUE THREAD

**Issue by DreamWuGit** [scroll-tech/zkevm-circuits#721]
### Describe the feature you would like
current constrain return_revert gadget responsible opcode is return or revert. has to check the difference.
refer to comments https://github.com/scroll-tech/zkevm-circuits/pull/633#discussion_r1273524994

### Additional context

https://app.asana.com/0/1203078612788501/1205200959683957/f

**Comment by DreamWuGit** [comment]
seems feasible by checking `revert` with `rw_counter_end_of_reversion` state as in fail step constraint `reversible_write_counter` in  https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1030

**Comment by naure** [comment]
See also section **E** in [this spec](https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/opcode/F3RETURN_FDREVERT.md).
