### ISSUE TITLE
improve sig/ecc circuit RLC usage

### ISSUE THREAD

**Issue by zhenfeizhang** [scroll-tech/zkevm-circuits#765]
### Describe the feature you would like

# currently the sig/ecc circuit are designed as follows:

- each base field `Fq` element is decomposed into three limbs, of `[88, 88, 80]` bits, respectively, stored in three `Fr` elements, and used for non-native arithmetics
- each base field `Fq` element is also decomposed into 32 bytes, stored in 32 `Fr` elements, and an `RLC` is computed for the 32 elements. This RLC will be looked up later

# Proposed solutions
1. we can simply RLC the 3 limbs. This will save some constraints from byte decomposition (and related range checks) and rlc computation.
2. we may use 3 limbs as the lookup arguments. This will remove the RLC completely and not relying on any phase 2 cells. The number of looked up cells will be doubled: we need 3 cells for x coordinate and 1 cell (sign) for y coordinate; that is for each group element we need 4 cells, increased from 2 cells (x_rlc and y_rlc)

**Comment by roynalnaruto** [comment]
@zhenfeizhang in the ECC circuit we still need a `Phase2` cell, for `input_rlc` to store the RLC'd bytes of the input to the pairing check operation.

Other than that, the rest RLCs can in fact be removed and each `Phase2` cell can be replaced with 3 `Phase1` cells representing the 3 limbs of that `Fq` element.

**Comment by lispc** [comment]
either solution will bring the notion "limbs" to the "caller circuit" (usually evm circuit).   It is easier for evm circuit to deal with bytes rather than limbs.    

 Currently limbs is only an implementation details on halo2-ecc circuits.
