### ISSUE TITLE
load_private points to circuit function does not check if the point is on curve

### ISSUE THREAD

**Issue by zhenfeizhang** [scroll-tech/zkevm-circuits#775]
https://github.com/scroll-tech/zkevm-circuits/blob/a96ca73d6bd0aa8bcb06a69e6e0dddcc3b49b559/zkevm-circuits/src/ecc_circuit.rs#L819

https://github.com/scroll-tech/halo2-lib/blob/2c225864227e74b207d9f4b9e08c4d5f1afc69a1/halo2-ecc/src/ecc/mod.rs#L557

https://github.com/scroll-tech/halo2-lib/blob/2c225864227e74b207d9f4b9e08c4d5f1afc69a1/halo2-ecc/src/ecc/mod.rs#L32

seems like `load_private` does not check the loaded point is a curve point. We need to added the check for both ecc circuit and ecdsa circuit

_Originally posted by @zhenfeizhang in https://github.com/scroll-tech/zkevm-circuits/pull/758#discussion_r1294716936_

**Comment by zhenfeizhang** [comment]
duplicated https://github.com/scroll-tech/zkevm-circuits/issues/563

**Comment by zhenfeizhang** [comment]
re opening this ticket. This is a soundness issue not only for ec precomiples but also for ecdsa circuit

**Comment by lispc** [comment]
fixed
