### ISSUE TITLE
test: support scroll l2 trace in integration-tests/mainnet.rs

### ISSUE THREAD

**Issue by lispc** [scroll-tech/zkevm-circuits#814]
we must discard prev_state_root/post_state_root in l1 block.
// zhuo: some constrains are invalid (eip2930 fee)

**Comment by noel2004** [comment]
An idea is to start with raw tx rather than geth traces. It's kinda like what we do in `TestCtx`

**Comment by lispc** [comment]
theoretically we can only test first tx inside block since you cannot fetch state **BEFORE TX** instead of before block?

**Comment by lispc** [comment]
lower priority now
