### ISSUE TITLE
feat: begin_tx precompile out of gas error

### ISSUE THREAD

**Issue by lispc** [scroll-tech/zkevm-circuits#834]
@darth-cy .   need this test for super circuit

**Comment by darth-cy** [comment]
New test outputs are added here: https://www.notion.so/scrollzkp/PR-850-Test-Outputs-a6f3ef3a7a5545fca1d4f8e187bfa402

**Comment by lispc** [comment]
in the issue, i mean the tx.to is a precompile contract. So if everything works ok, the StructLog inside trace should be empty since no opcode is executed.
