### ISSUE TITLE
post mainnet development

### ISSUE THREAD

**Issue by lispc** [scroll-tech/zkevm-circuits#883]
### routine developments

1. upgrade deps: ff / group / halo2-libs / snark-verfier / halo2 / revm / ethers-rs / rust (check whether we can use stable)...
2. https://github.com/scroll-tech/zkevm-circuits/issues/884 Use halo2 circuit-params feature (by using this, we can enable ecc/sig circuits testing inside `CircuitTestBuilder` more efficiently
3. re-unify with upstream: at least check whether we should merge the hi-lo refactor
4. https://github.com/scroll-tech/zkevm-circuits/issues/882 refactor rw: restrict read/write must happen through rw
5. https://github.com/scroll-tech/zkevm-circuits/issues/840 refactor: use preStateTracer
8. fast & accurate ccc, especially for poseidon

more https://www.notion.so/scrollzkp/Status-and-Future-of-zkevm-circuits-2023-07-f2643cf83ee64709858d83665e6f9221

### big new features

1. the 3 hash precompile
2. remove usage of RLC inside shared tables, paving road for future hybrid circuit.
3. eip4844: how to use this to reduce l1 finialization gas, not support eip4844 inside zkevm

### random ideas

1. is it possible to use beacon chain randao as the fiat-shamir randomness?

### bug fixes & soundness issues

1. decide whether & how should we constrain tx receipts

### toward scroll-zkevm 2.0

rewrite of constrain system and whole circuits design

**Comment by lightsing** [comment]
- the GitHub actions also need upgrade, the action-rs is no longer maintained.
- we should deprecate usage of `lazy_static` in favour of `once_cell` related to: https://github.com/rust-lang-nursery/lazy-static.rs/issues/214

**Comment by lightsing** [comment]
We may also setup `cargo deny` ci to check our dependency licenses especially when new deps are added.

**Comment by lispc** [comment]
> We may also setup `cargo deny` ci to check our dependency licenses especially when new deps are added.

great. we need this. At least check it once.
