### ISSUE TITLE
CI speed / bitwise lookup table / faster MockProver

### ISSUE THREAD

**Issue by lispc** [scroll-tech/zkevm-circuits#94]
currently it costs more than 30 minutes to finish CI in appliedzkp/zkevm-circuits. I test it locally and find tests of bitwise op cost much time. (Other op test cost 10-30s, while bitwise op test needs 150-180s).  Then I find the reason behind this is that bitwise op test needs full lookup table ( with bitwise lookup table, eg bitwise xor table has 256*256 entries, same for bitwise and/or) and other ops need stripped lookup table (without bitwise table).    Using full lookup table needs more rows, namely more degree for the circuit.

In MockProver::verify, every gate and every lookup are evaluated on **every row** （ including the empty/padding rows).    So if we can verify on less rows, we can make verify much faster.   We can add a method call `verify_at_rows(rows_ids: Box<Interator<usize>>)`, we know which rows can be skipped(padding rows, and non q_step rows), so from the application circuit side we can provide much less row ids to verifier to speedup verification. 

We can do this after kilic rebase appliedzkp/halo2 on zcash/halo2.

**Comment by HAOYUatHZ** [comment]
seems we can close this via https://github.com/appliedzkp/zkevm-circuits/pull/354?

**Comment by lispc** [comment]
yes
